### ISSUE TITLE
Fail to build in CUDA11

### ISSUE THREAD

**Issue by SJLNNU** [gdlg/pytorch_nms#8]
Hi, thank you for your work.
I might have some troubles in building NMS .

There is my device and CUDA info ,I am using Linux ubuntu-18.04.
![QQ截图20211227150414](https://user-images.githubusercontent.com/31751988/147447932-2d61574c-dad4-4a3e-9670-a77e7a396cf0.png)
![QQ截图20211227150312](https://user-images.githubusercontent.com/31751988/147447934-2af251cd-1de3-4202-a4ba-7eadb8564c94.png)

After I enter `python setup install`
there is what i got:
(laneatt_test) njnu@njnu-System-Product-Name:~/Codes/Image_software/Lane/LaneATT/lib/nms$ python setup.py install
running install
running bdist_egg
running egg_info
writing src/nms.egg-info/PKG-INFO
writing dependency_links to src/nms.egg-info/dependency_links.txt
writing top-level names to src/nms.egg-info/top_level.txt
reading manifest file 'src/nms.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/nms.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'nms.details' extension
Emitting ninja build file /home/njnu/Codes/Image_software/Lane/LaneATT/lib/nms/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] :/usr/local/cuda-11.0/bin/nvcc -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include/TH -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-11.0/include -I/home/njnu/anaconda3/envs/laneatt_test/include/python3.7m -c -c /home/njnu/Codes/Image_software/Lane/LaneATT/lib/nms/src/nms_kernel.cu -o /home/njnu/Codes/Image_software/Lane/LaneATT/lib/nms/build/temp.linux-x86_64-3.7/src/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=details -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/njnu/Codes/Image_software/Lane/LaneATT/lib/nms/build/temp.linux-x86_64-3.7/src/nms_kernel.o
:/usr/local/cuda-11.0/bin/nvcc -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include/TH -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-11.0/include -I/home/njnu/anaconda3/envs/laneatt_test/include/python3.7m -c -c /home/njnu/Codes/Image_software/Lane/LaneATT/lib/nms/src/nms_kernel.cu -o /home/njnu/Codes/Image_software/Lane/LaneATT/lib/nms/build/temp.linux-x86_64-3.7/src/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=details -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
/bin/sh: 1: :/usr/local/cuda-11.0/bin/nvcc: not found
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1522, in _run_ninja_build
    env=env)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

Please help me out ,thanks .

**Comment by SJLNNU** [comment]
If anyone building nms module with CUDA11 and RTX3090 add  `export TORCH_CUDA_ARCH_LIST="8.0"` before you setup.

**Comment by HoangTienDuc** [comment]
Hi, @SJLNNU Thank you for your answer. However, I failed to build in Cuda 11.4.

Could you please give some advice to make it done? Thanks

Step to reproduce:
```
export TORCH_CUDA_ARCH_LIST="8.0"
python3 setup.py install
```

Error logs:
```
running install
running bdist_egg
running egg_info
writing src/nms.egg-info/PKG-INFO
writing dependency_links to src/nms.egg-info/dependency_links.txt
writing top-level names to src/nms.egg-info/top_level.txt
/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'src/nms.egg-info/SOURCES.txt'
writing manifest file 'src/nms.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
    self.build()
  File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
    self._check_cuda_version()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 781, in _check_cuda_version
    raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
RuntimeError: 
The detected CUDA version (11.4) mismatches the version that was used to compile
PyTorch (10.2). Please make sure to use the same CUDA versions
```

**Comment by SJLNNU** [comment]
> Hi, @SJLNNU Thank you for your answer. However, I failed to build in Cuda 11.4.
> 
> Could you please give some advice to make it done? Thanks
> 
> Step to reproduce:
> 
> ```
> export TORCH_CUDA_ARCH_LIST="8.0"
> python3 setup.py install
> ```
> 
> Error logs:
> 
> ```
> running install
> running bdist_egg
> running egg_info
> writing src/nms.egg-info/PKG-INFO
> writing dependency_links to src/nms.egg-info/dependency_links.txt
> writing top-level names to src/nms.egg-info/top_level.txt
> /usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
>   warnings.warn(msg.format('we could not find ninja.'))
> reading manifest file 'src/nms.egg-info/SOURCES.txt'
> writing manifest file 'src/nms.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> running build_ext
> Traceback (most recent call last):
>   File "setup.py", line 7, in <module>
>     cmdclass={'build_ext': BuildExtension})
>   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
>     self.do_egg_install()
>   File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
>     self.run_command('bdist_egg')
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
>     cmd = self.call_command('install_lib', warn_dir=0)
>   File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
>     self.run_command(cmdname)
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
>     self.build()
>   File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
>     self.run_command('build_ext')
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 78, in run
>     _build_ext.run(self)
>   File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
>     self.build_extensions()
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
>     self._check_cuda_version()
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 781, in _check_cuda_version
>     raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
> RuntimeError: 
> The detected CUDA version (11.4) mismatches the version that was used to compile
> PyTorch (10.2). Please make sure to use the same CUDA versions
> ```

Hi there ，it seems your Current  CUDA version mismatches the PyTorch. Maybe you changed the CUDA version from 10.2 to 11.4,but dont forget update  the PyTorch.

**Comment by HoangTienDuc** [comment]
Thank you!
